util/grub-protect: Fix compilation error when optimization is O2
When the host utilities are compiled with optimization level O2
or higher, grub_protect.c fails to compile with an error like:
In function ‘protect_tpm2_seal’,
    inlined from ‘protect_tpm2_add’ at util/grub-protect.c:1014:9:
util/grub-protect.c:637:35: error: ‘key_size’ may be used
uninitialized [-Werror=maybe-uninitialized]
  637 |   inSensitive.sensitive.data.size = clearTextLength;

This is only detected by the compiler with higher levels of
optimization because the compiler does a deeper program analysis.

Correct this by initializing key_size to zero at declaration.

Signed-off-by: Andrew Hamilton <adhamilt@gmail.com>
Reviewed-by: Gary Lin <glin@suse.com>
Reviewed-by: Avnish Chouhan <avnish@linux.ibm.com>
Reviewed-by: Sudhakar Kuppusamy <sudhakar@linux.ibm.com>
Reviewed-by: Leo Sandoval <lsandova@redhat.com>
Part-of: <https://gitlab.freedesktop.org/gnu-grub/grub/-/merge_requests/261>