osdep: Fix linker error on a macOS host machine
add_multiple_nvme_bootdevices to help PowerPC Linux servers find multi-path NVMe
drives. However, that function calls nvme_get_syspath, of_path_get_nvme_nsid,
and xrealpath, which are depends entirely on Linux sysfs code. Because mac host
lacks a Linux kernel or a /sys/ filesystem, the file defining nvme_get_syspath
is skipped by the compiler, causing grub_mkrescue at the linker. This patch fixes
the linker error.

Build step on macOS:
./bootstrip
./configure --prefix=/usr --with-platform=ieee1275 --target=powerpc64-linux-gnu
make -j8

Error:
Undefined symbols for architecture arm64:
  "_nvme_get_syspath", referenced from:
      _add_multiple_nvme_bootdevices in grub_mkrescue-platform_unix.o
  "_of_path_get_nvme_nsid", referenced from:
      _add_multiple_nvme_bootdevices in grub_mkrescue-platform_unix.o
  "_xrealpath", referenced from:
      _add_multiple_nvme_bootdevices in grub_mkrescue-platform_unix.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Signed-off-by: Sudhakar Kuppusamy <sudhakar@linux.ibm.com>
Reviewed-by: Leo Sandoval <lsandova@redhat.com>
Part-of: <https://gitlab.freedesktop.org/gnu-grub/grub/-/merge_requests/152>